apiVersion: v1
kind: ServiceAccount
metadata:
  name: Bob

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-bob
subjects:
  - kind: ServiceAccount
    name: Bob
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io