prometheus:
  ingress:
      enabled: true
      annotations: {
        kubernetes.io/ingress.class: nginx,
        kubernetes.io/tls-acme: "true",
        cert-manager.io/cluster-issuer: "letsencrypt-prod",
        cert-manager.io/acme-challenge-type: http01
      }
      path: /
      hosts:
        - prometheus.35.194.23.119.nip.io
      tls:
        - secretName: prometheus.35.194.23.119.nip.io
          hosts:
            - prometheus.35.194.23.119.nip.io
  prometheusSpec:
    tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
    serviceMonitorSelectorNilUsesHelmValues: false
grafana:
  ingress:
      enabled: true
      annotations: {
        kubernetes.io/ingress.class: nginx,
        kubernetes.io/tls-acme: "true",
        cert-manager.io/cluster-issuer: "letsencrypt-prod",
        cert-manager.io/acme-challenge-type: http01
      }
      path: /
      hosts:
        - grafana.35.194.23.119.nip.io
      tls:
        - secretName: grafana.35.194.23.119.nip.io
          hosts:
            - grafana.35.194.23.119.nip.io
