kind: Pod 
apiVersion: v1 
metadata:
  name: web-deweaty
spec:
  volumes:
    - name: app
      emptyDir: {}
  containers: 
    - name: web
      image: dweaty96/web-otus-1:latest
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-web
      image: busybox:1.28
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app
